name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta'

jobs:
  build-plugin:
    uses: ./.github/workflows/build-plugin.yml

  build-zip-upload:
    needs: build-plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download canonical zip artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-plugin.outputs.zip-artifact-name }}
          path: .

      # Publie la release
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ needs.build-plugin.outputs.zip-file-name }}
          generateReleaseNotes: true
